rentmanagement/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import url
from django.contrib.auth import views

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

from django.contrib.auth import views as auth_views
from rentmanagement.views import dashboard_view
from django.contrib.auth.views import LogoutView
from rentmanagement.views import sites_input_view
from rentmanagement.views import person_input_view
from rentmanagement.views import property_input_view
from rentmanagement.views import agreement_input_view
from rentmanagement.views import agreement_view
from rentmanagement.views import sites_view
from rentmanagement.views import properties_view
from rentmanagement.views import person_view
from rentmanagement.views import error_view
from rentmanagement.views import agreement_detail_view
from rentmanagement.views import agreement_detail_view_activate

from rentmanagement.views import rent_input_view
from rentmanagement.views import rent_input_view_new
from rentmanagement.views import rent_delete_view
from rentmanagement.views import rent_delete_view_new
from rentmanagement.views import advance_delete_view
from rentmanagement.views import advance_delete_view_new
from rentmanagement.views import adv_input_view_new
from rentmanagement.views import rent_detail_view
from rentmanagement.views import advance_input_view
from rentmanagement.views import advance_detail_view
from rentmanagement.views import security_input_view
from rentmanagement.views import security_detail_view
from rentmanagement.views import sites_edit_view
from rentmanagement.views import person_edit_view
from rentmanagement.views import property_edit_view
from rentmanagement.views import agreement_detail_view_agrm
from rentmanagement.views import agreement_edit_view

from rentmanagement.views import agreement_activated_view

from rentmanagement.views import update_agreement_status_view
from rentmanagement.views import update_agreement_status_new_view

from rentmanagement.views import autocomplete_div_view
from rentmanagement.views import autocomplete_postcode_view

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/login/', auth_views.LoginView.as_view(template_name="agreement/login.html"), name='login'),
    # path('accounts/', include('django.contrib.auth.urls')),
    # url(r'^login/$', auth_views.login, {'template_name': 'agreement/login.html'}, name='login'),
    url( r'^login/$',auth_views.LoginView.as_view(template_name="agreement/login.html"), name="login"),
    path('accounts/profile/',dashboard_view,name='dashboard_view'),
    path('sites_input_view/',sites_input_view,name='sites_input_view'),
    url(r'^sites_edit_view/?(?P<id>[^/]+)/$', sites_edit_view, name="sites_edit_view"),
    url(r'^person_edit_view/?(?P<id>[^/]+)/$', person_edit_view, name="person_edit_view"),
    url(r'^property_edit_view/?(?P<id>[^/]+)/$', property_edit_view, name="property_edit_view"),
    url(r'^rent_delete_view/?(?P<id>[^/]+)/$', rent_delete_view, name="rent_delete_view"),
    url(r'^rent_delete_view_new/?(?P<id>[^/]+)/$', rent_delete_view_new, name="rent_delete_view_new"),
    url(r'^advance_delete_view/?(?P<id>[^/]+)/$', advance_delete_view, name="advance_delete_view"),
    url(r'^advance_delete_view_new/?(?P<id>[^/]+)/$', advance_delete_view_new, name="advance_delete_view_new"),
    path('sites/',sites_view,name='sites_view'),
    path('update_agr_status/<id>/',update_agreement_status_view,name='update_agreement_status_view'),
    path('update_agr_status_new/<id>/',update_agreement_status_new_view,name='update_agreement_status_new_view'),
    path('person_input/',person_input_view,name='person_input_view'),
    path('person/',person_view,name='person_view'),
    path('error/',error_view,name='error_view'),
    path('property_input/',property_input_view,name='property_input_view'),
    path('property/',properties_view,name='properties_view'),
    path('agreement/',agreement_input_view,name='agreement_input_view'),
    url(r'^agreement_edit/?(?P<id>[^/]+)/$', agreement_edit_view, name="agreement_edit_view"),
    # path('agreement_edit/',agreement_edit_view,name='agreement_edit_view'),
    path('agreement_result/',agreement_view,name='agreement_view'),
    path('agreement_final_result/',agreement_activated_view,name='agreement_activated_view'),
    url(r'^agreement/?(?P<pk>[^/]+)/$', agreement_detail_view, name="agreement_detail_view"),
    url(r'^agreement_detail_activate/?(?P<pk>[^/]+)/$', agreement_detail_view_activate, name="agreement_detail_view_activate"),
    url(r'^agreement_rent/(?P<pk>\d+)/$', agreement_detail_view_agrm, name="agreement_detail_view_agrm"),
    url(r'^rents/?(?P<ag>[^/]+)/$', rent_detail_view, name="rent_detail_view"),
    url(r'^rent_input_view_new/?(?P<id>[^/]+)/$', rent_input_view_new, name="rent_input_view_new"),
    url(r'^adv_input_view_new/?(?P<id>[^/]+)/$', adv_input_view_new, name="adv_input_view_new"),
    path('rent_input_view/',rent_input_view,name='rent_input_view'),
    url(r'^securities/?(?P<ag>[^/]+)/$', security_detail_view, name="rent_security_view"),
    path('security_input_view/',security_input_view,name='security_input_view'),
    url(r'^advancepayments/?(?P<ag>[^/]+)/$', advance_detail_view, name="advance_detail_view"),
    path('advance_input_view/',advance_input_view,name='advance_input_view'),
    # path('success/', views.success, name='success'),
    url(r'^autocomplete_div_view/', autocomplete_div_view,name='autocomplete_div_view'),
    url(r'^autocomplete_postcode_view/', autocomplete_postcode_view,name='autocomplete_postcode_view'),
    url( r'^logout/$',auth_views.LogoutView.as_view(), {'next_page': '/'},name="logout"),
    # url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),


    # path('accounts/', include('django.contrib.auth.urls')),
]

agreement/models.py
from django.db import models
from datetime import date

from django.contrib.auth.models import User
from django.utils import timezone
# from django.forms import ModelForm

# Create your modefrom django.db import models


class Site(models.Model):
    site_code= models.CharField(max_length=4)
    site_extension= models.IntegerField(max_length=20,blank=True,null=True)
    display_area=models.IntegerField(max_length=20,null=True,blank=True,help_text='size of the site in sft',default=0)
    storage_area_inside=models.IntegerField(max_length=20,null=True,blank=True, help_text='size of the site in sft')
    storage_area_outside=models.IntegerField(max_length=20,null=True,blank=True, help_text='size of the site in sft')
    lattitude=models.DecimalField(blank=True,null=True,max_digits=30,decimal_places=4)
    longitude=models.DecimalField(blank=True,null=True,max_digits=30,decimal_places=4)
    # CharField(max_length=20,unique=True)
    # site_description = models.CharField(max_length=450)
    site_size = models.IntegerField(max_length=100,help_text='size of the site in sft', null=True)
    district = models.CharField(max_length=20)
    area = models.CharField(max_length=20)
    site_type=models.CharField(max_length=20,choices=[
        ('SHOP', 'SHOP'),
        ('WAREHOUSE', 'WAREHOUSE'),
        ('SERVICE CENTER','SERVICE CENTER'),
        ('RESIDENT','RESIDENT'),
        ('STORE','STORE' ),
        ('OFFICE','OFFICE')])
    # last_modified_by=models.CharField(max_length=20,blank=True)
    entry_by=models.CharField(max_length=20,blank=True)
    entry_date = models.DateField(null=True)
    # last_modified_date=models.DateField(blank=True)
    # branch_manager = models.CharField(max_length=100)

    # category = models.CharField(max_length=200,choices=[
    #     ('site_allocation', 'site_allocation'),
    #     ('renew', 'renew')
    #
    # ])


    # quantity = models.CharField(max_length=20)
    # model_code = models.CharField(max_length=20,null=True)


    # address=models.CharField(max_length=100,default="")
    def __str__(self):
        if str(self.site_extension)=='':
            return self.site_code
        else:
            return self.site_code+'-'+str(self.site_extension)
    def save(self,*args, **kwargs):
        if not self.entry_date:
            self.entry_date=timezone.now()
        self.modified=timezone.now()
        return super(Site,self).save(*args,**kwargs)



class Person(models.Model):
    name=models.CharField(max_length=100)
    person_status=models.CharField(max_length=100,default='active')
    person_type=models.CharField(max_length=30,choices=[
        ('Organization', 'Organization'),
        ('Individual', 'Individual'),
        ('Others','Others')])
    # type=models.CharField(verbose_name='Lessor type',max_length=30,
    # choices=[
    #     ('lessee', 'lessee'),
    #     ('lessor', 'lessor'),
    #     ('witness', 'witness')], )
    nid=models.CharField(verbose_name='NID',null=True,max_length=20,blank=True)
    tin=models.CharField(verbose_name='TIN',null=True,blank=True,max_length=20)
    email=models.CharField(max_length=40,null=True,blank=True)
    phone=models.CharField(max_length=20,null=True,blank=True)

    dealing_person_status=models.CharField(max_length=10,verbose_name='Is there any dealing person other than lessor?', choices=[('Yes','Yes'),('No','No')])
    address=models.CharField(max_length=50,blank=True, null=True)
    # sis_supplier_code=models.CharField(max_length=50,blank=True)

    # address=models.CharField(max_length=450)
    sis_supplier_code=models.CharField(max_length=900,blank=True)
    name_of_dealing_person=models.CharField(max_length=50,blank=True,null=True)
    phone_number_of_dealing_person=models.CharField(max_length=50,blank=True,null=True)
    email_of_dealing_person=models.EmailField(max_length=30,blank=True,null=True)
    relationship=models.CharField(max_length=30,blank=True,null=True)
    division=models.CharField(max_length=40)
    district=models.CharField(max_length=40)
    thana=models.CharField(max_length=40)
    postcode=models.CharField(max_length=40)
    village=models.CharField(max_length=40)
    entry_by=models.CharField(max_length=20,blank=True)
    entry_date = models.DateField(null=True)




    def __str__(self):
        return self.name
    def save(self,*args, **kwargs):
        if not self.entry_date:
            self.entry_date=timezone.now()
        self.modified=timezone.now()
        return super(Person,self).save(*args,**kwargs)

class Properties(models.Model):
    type=models.CharField(verbose_name='Availability',max_length=100,blank=True,null=True,choices=[
        ('available', 'available'),
        (' not available', ' not available')])
    desc=models.CharField(max_length=450, verbose_name='Address',blank=True,null=True)
    status=models.CharField(max_length=30, blank=True,null=True,choices=[
        ('active', 'active'),
        (' not active', ' not active')])

    property_size = models.IntegerField(max_length=100,help_text='size of the site in sft', blank=True,null=True)
    # area=models.CharField(max_length=20)
    # city=models.CharField(max_length=20)
    # district=models.CharField(max_length=20)
    # division=models.CharField(max_length=20)

    division=models.CharField(max_length=40,blank=True,null=True)
    district=models.CharField(max_length=40,blank=True,null=True)
    thana=models.CharField(max_length=40,blank=True,null=True)
    postcode=models.CharField(max_length=40,blank=True,null=True)
    village=models.CharField(max_length=40,blank=True,null=True)
    number_of_owner=models.IntegerField(max_length=20,choices=[
        (1, 1),
        (2, 2),
        (3,3),
        (4,4),
        (5,5 )])
    owner1=models.ForeignKey(Person,on_delete=models.CASCADE,related_name='first_person')
    percentage_of_first_owner=models.IntegerField()
    owner2=models.ForeignKey(Person,on_delete=models.CASCADE, related_name='second_person',null=True, blank=True)
    percentage_of_second_owner=models.IntegerField(max_length=20,null=True, blank=True)
    owner3=models.ForeignKey(Person,on_delete=models.CASCADE, related_name='third_person',null=True, blank=True)
    percentage_of_third_owner=models.IntegerField(max_length=20,null=True, blank=True)
    owner4=models.ForeignKey(Person,on_delete=models.CASCADE, related_name='fourth_person',null=True, blank=True)
    percentage_of_fourth_owner=models.IntegerField(max_length=20,null=True, blank=True)
    owner5=models.ForeignKey(Person,on_delete=models.CASCADE, related_name='fifth_person',null=True, blank=True)
    percentage_of_fifth_owner=models.IntegerField(max_length=20,null=True, blank=True)

    number_of_sites=models.IntegerField(max_length=20,choices=[
        (1, 1),
        (2, 2),
        (3,3),
        (4,4)])
    site1=models.ForeignKey(Site,on_delete=models.CASCADE,related_name='first_site')
    percentage_of_first_site=models.IntegerField(max_length=20)
    site2=models.ForeignKey(Site,on_delete=models.CASCADE, related_name='second_site',null=True, blank=True)
    percentage_of_second_site=models.IntegerField(max_length=20,null=True,blank=True)
    site3=models.ForeignKey(Site,on_delete=models.CASCADE, related_name='third_site',null=True, blank=True)
    percentage_of_third_site=models.IntegerField(max_length=20,null=True, blank=True)
    site4=models.ForeignKey(Site,on_delete=models.CASCADE, related_name='fourth_site',null=True, blank=True)
    percentage_of_fourth_site=models.IntegerField(max_length=20,null=True, blank=True)

    entry_by=models.CharField(max_length=20,blank=True)
    entry_date = models.DateField(null=True)

    def __str__(self):
        return self.division+' '+self.district+' '+self.thana+' '+self.village
    def save(self,*args, **kwargs):
        if not self.entry_date:
            self.entry_date=timezone.now()
        self.modified=timezone.now()
        return super(Properties,self).save(*args,**kwargs)


class Agreement(models.Model):
    id= models.IntegerField(max_length=10000000, primary_key=True),
    agrm_id=models.CharField(max_length=30,null=True,blank=True,default="hello")
    agreement_date = models.DateField(null=True,blank=True)
    total_rou=models.IntegerField(null=True, blank=True)
    # tenure_year=models.IntegerField()
    effected_date_as_actual= models.DateField(null=True,blank=True,verbose_name='Effective date as actual')
    effected_date_as_per_agreement = models.DateField(null=True,blank=True,verbose_name='Effective date as per agreement')
    expiry_date = models.DateField(null=True,blank=True,verbose_name='Expiry date')
    tenure_month=models.IntegerField(null=True,blank=True)
    agreement_cat_type=models.CharField(verbose_name='Agreement category type',max_length=90,choices=[
        ('Relocation', 'Relocation'),
        ('New', 'New'),
        ('Old', 'Old'),
        ('Renewal','Renewal'),
        ('Extension','Extension'),
        ('Additional Space','Additional Space'),
        ('Amendment Of Lease Agreement -Sep-2019','Amendment Of Lease Agreement -Sep-2019'),
        ('Ground floor','Ground floor'),
        ('Possession purchase','Possession purchase'),
        ('Renewal(Extension)','Renewal(Extension)'),
        ('Space-Extension','Space-Extension')])
    termination_clause=models.CharField(max_length=70,choices=[
            ('Both parties agree to uninterrupted tenancy period', 'Both parties agree to uninterrupted tenancy period'),
            ('Both parties Negotiator', 'Both parties Negotiator'),
            ('Both parties_1 Month prior written notice','Both parties_1 Month prior written notice'),
            ('Both parties_12 Months prior written notice','Both parties_12 Months prior written notice'),
            ('Both parties_3 Months prior written notice','Both parties_3 Months prior written notice'),
            ('Both parties_4 Months prior written notice','Both parties_4 Months prior written notice'),

templates/agreement/advance.html
{% extends 'agreement/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row mb-2">
  <div class="col-sm-6">
    <h1 class="m-0 text-dark">Advance Payment Line</h1>
  </div>
</div>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" value='save' class="btn btn-primary">Add Advance Payment line</button>
  </form>
{% endblock %}

templates/agreement/advance_detail.html
{% extends 'agreement/basefile.html' %}
{% block content %}
<section class="content">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Advance Payment line Data</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
            <div class="row">
              <div class="col-sm-12 col-md-6">
                <a href="{%url 'advance_input_view' %}"  style="margin: 10px" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Add New Advance Payment Line</a>
                <!-- <button click="{%url 'agreement_input_view' %}" style="margin: 10px"type="button" name="button" class="btn btn-primary">Add New Agreement</button> -->
              </div>
              <div class="col-sm-12 col-md-6">



              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                  <thead>
                    <tr role="row">
                      <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Rent Line Id</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">From Date</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending"> To Date</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Line Amount</th>

                    </tr>
                  </thead>
                  <tbody>
                    {% for rent in rent %}
                    <tr>
                      <td>{{ rent.advance_payment_line_id }}</td>
                      <td>{{ rent.from_line_date }}</td>
                      <td>{{ rent.to_line_date }}</td>
                      <td>{{ rent.total_line_amount }}</td>

                    </tr>
                    {% endfor %}
                  </tbody>
                  <!-- <tfoot>
                    <tr>
                      <th rowspan="1" colspan="1">Rendering engine</th>
                      <th rowspan="1" colspan="1">Browser</th>
                      <th rowspan="1" colspan="1">Platform(s)</th>
                      <th rowspan="1" colspan="1">Engine version</th>
                      <th rowspan="1" colspan="1">CSS grade</th>
                    </tr>
                  </tfoot> -->
                </table>
              </div>
            </div>
            <div class="row">
              <!-- <div class="col-sm-12 col-md-5">
                <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
              </div> -->
              <!-- <div class="col-sm-12 col-md-7">
                <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                  <ul class="pagination">
                    <li class="paginate_button page-item previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li>
                    <li class="paginate_button page-item active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0" class="page-link">1</a></li>
                    <li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0" class="page-link">2</a></li>
                    <li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0" class="page-link">3</a></li>
                    <li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0" class="page-link">4</a></li>
                    <li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0" class="page-link">5</a></li>
                    <li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0" class="page-link">6</a></li>
                    <li class="paginate_button page-item next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0" class="page-link">Next</a></li>
                  </ul>
                </div>
              </div> -->
            </div>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->


      <!-- /.card -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>

{% endblock %}

templates/agreement/rent.html
{% extends 'agreement/base.html' %}

{% load crispy_forms_tags %}

{% block content %}


<div class="row mb-2">
  <div class="col-sm-6">
    <h1 class="m-0 text-dark">Rent Line</h1>
  </div>
</div>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}

    
    <button type="submit" value='save' class="btn btn-primary">Add Rentline</button>
  </form>
{% endblock %}

templates/agreement/sites.html
{% extends 'agreement/base.html' %}

{% load crispy_forms_tags %}

{% block content %}




<div class="row mb-2">
  <div class="col-sm-6">
    <h1 class="m-0 text-dark">Sites</h1>

  </div>
</div>
<form method="POST">
  {% csrf_token %}
  {{ form|crispy }}

  <div class="card card-default">
    <div class="card-header">
      <h3 class="card-title">Site Details</h3>

      <!-- <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
              <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
            </div> -->
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <div class="row">
        <div class="col-md-4">
          <div id="div_id_site_code" class="form-group"> <label for="id_site_code" class=" requiredField">
              Site code<span class="asteriskField">*</span> </label>
            <div class=""> <input style="text-transform: uppercase" type="text" name="site_code" pattern=".{4,}"   required title="4 characters minimum" maxlength="4" class="textinput textInput form-control" required="" id="id_site_code"> </div>
            <small id="hint_id_site_size" class="form-text text-muted">Site code Example: DGNB</small>
          </div>





        </div>
        <!-- /.col -->

        <!-- /.col -->
        <!-- </div> -->
        <!-- /.row -->

        <div class="col-md-4">
          <div id="div_id_area" class="form-group"> <label for="id_area" class=" requiredField">
              Area<span class="asteriskField">*</span> </label>
            <div class=""> <input type="text" name="area" maxlength="20" class="textinput textInput form-control" required="" id="id_area"> </div>
          </div>
        </div>



        <div class="col-md-4">
          <div id="div_id_district" class="form-group"> <label for="id_district" class=" requiredField">
              District<span class="asteriskField">*</span> </label>
            <div class=""> <input type="text" name="district" maxlength="20" class="textinput textInput form-control" required="" id="id_district"> </div>
          </div>
          <!-- /.col -->
        </div>

      </div>
      <div class="row">
        <div class="col-md-6">
          <div id="div_id_site_type" class="form-group"> <label for="id_site_type" class=" requiredField">
              Site type<span class="asteriskField">*</span> </label>
            <div class=""> <select name="site_type" class="select form-control" required="" id="id_site_type">
                <option value="" selected="">---------</option>
                <option value="SHOP">SHOP</option>
                <option value="WAREHOUSE">WAREHOUSE</option>
                <option value="SERVICE CENTER">SERVICE CENTER</option>
                <option value="RESIDENT">RESIDENT</option>
                <option value="STORE">STORE</option>
                <option value="OFFICE">OFFICE</option>

              </select> </div>
          </div>
        </div>



        <!-- /.col -->
        <div class="col-md-6">
          <div id="div_id_site_size" class="form-group"> <label for="id_site_size" class=" requiredField">
              Site size<span class="asteriskField">*</span> </label>
            <div class=""> <input type="number" name="site_size" class="numberinput form-control" required="" id="id_site_size"> <small id="hint_id_site_size" class="form-text text-muted">size of the site in sft</small> </div>
          </div>
        </div>
        <!-- /.col -->
        <!-- </div> -->
        <!-- /.row -->



      </div>


    </div>

  </div>
  <div class="card card-default">
    <div class="card-header">
      <h3 class="card-title">Space Allocation</h3>

      <!-- <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
              <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
            </div> -->
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <div class="row">
        <div class="col-md-4">

          <div id="div_id_display_area" class="form-group"> <label for="id_display_area" class="">
              Display area
            </label>
            <div class=""> <input type="number" name="display_area" class="numberinput form-control" id="id_display_area"> <small id="hint_id_display_area" class="form-text text-muted">size of the site in sft</small> </div>
          </div>


        </div>

        <div class="col-md-4">

          <div id="div_id_storage_area_inside" class="form-group"> <label for="id_storage_area_inside" class="">
              Storage area inside
            </label>
            <div class=""> <input type="number" name="storage_area_inside" class="numberinput form-control" id="id_storage_area_inside"> <small id="hint_id_storage_area_inside" class="form-text text-muted">size of the site in sft</small> </div>
          </div>

        </div>
        <div class="col-md-4">

          <div id="div_id_storage_area_outside" class="form-group"> <label for="id_storage_area_outside" class="">
              Storage area outside
            </label>
            <div class=""> <input type="number" name="storage_area_outside" class="numberinput form-control" id="id_storage_area_outside"> <small id="hint_id_storage_area_outside" class="form-text text-muted">size of the site in sft</small> </div>
          </div>

        </div>


        <!-- /.col -->

        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card-body -->



  <div class="card card-default">
    <div class="card-header">
      <h3 class="card-title">GPS Location</h3>

      <!-- <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
              <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
            </div> -->
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <div class="row">
        <div class="col-md-6">

          <div id="div_id_lattitude" class="form-group"> <label for="id_lattitude" class="">
              Lattitude
            </label>
            <div class=""> <input type="number" name="lattitude" step="0.0001" class="numberinput form-control" id="id_lattitude"> </div>
          </div>



        </div>
        <!-- /.col -->
        <div class="col-md-6">
          <div id="div_id_longitude" class="form-group"> <label for="id_longitude" class="">
              Longitude
            </label>
            <div class=""> <input type="number" name="longitude" step="0.0001" class="numberinput form-control" id="id_longitude"> </div>
          </div>
          <!-- /.form-group -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.card-body -->
  </div>





  <button type="submit" value='save' class="btn btn-primary">Save</button>
  <a href="javascript:history.go(-1)" value='cancel' class="btn btn-primary">Cancel</a>
</form>
{% endblock %}